# Generated by Django 3.2.19 on 2023-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iocn', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('des', models.TextField()),
            ],
        ),
    ]
