# Generated by Django 4.2.6 on 2023-10-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='des',
        ),
    ]
