# Generated by Django 4.2.6 on 2023-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='des',
            field=models.TextField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
