# Generated by Django 4.2.6 on 2023-10-10 06:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dest',
            field=tinymce.models.HTMLField(default=20),
            preserve_default=False,
        ),
    ]
