# Generated by Django 4.2.6 on 2023-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.FileField(default=None, null=True, upload_to='news/'),
        ),
    ]
