# Generated by Django 4.2.6 on 2023-10-10 17:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='savedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertitle', models.CharField(max_length=20)),
                ('userdest', tinymce.models.HTMLField()),
            ],
        ),
    ]
